settings:
  # Time in seconds to sync everyone's nicknames
  sync-interval: 60  
  # Your essentials prefix.
  # Will be removed from the beginning of your Minecraft nickname before syncing to Discord.
  essentials-nick-prefix: "*"
  # Your essentials suffix.
  # Will be removed from the end of your Minecraft nickname before syncing to Discord.
  essentials-nick-suffix: "§r"
  # What name to use by default for both Minecraft and Discord
  # This can be changed by the player as long as they have the permission discordnick.sync
  # Can either be "minecraft", "discord", or "off"
  default-sync: discord