# DO NOT CHANGE THIS
internal:
  plugin-version: "1.0.4"
# DO NOT CHANGE THIS

# What name to use by default for both Minecraft and Discord.
# This can be changed by the player as long as they have the permission discordnick.use
# Can either be "minecraft", "discord", or "off"
default-sync: minecraft

# What to replace whitespace characters with when syncing from Discord to Minecraft.
# Keep this as "" to remove whitespace characters.
# Set this to " " to keep as spaces.
# Set this to anything else to replace it with that.
replace-whitespaces-with: ""

# Whether to combine whitespace characters together before replacing them with the value above.
merge-whitespaces-before-replacing: true

# Type @<minecraft username|essentials nickname|discord nickname> in minecraft chat to also ping the linked account on Discord.
# Mentions also work when pinged on Discord, except for the mention color.
mentions:
  # Set to false to disable mentions.
  enabled: true

  # The sound that a player hears when they are mentioned.
  # You must manually disable MinecraftMentionSound in DiscordSRV's config.yml if you don't want multiple sounds.
  play-sound:
    enabled: true
    # Can be any value listed under "Java Edition values" on this webpage: https://minecraft.wiki/w/Sounds.json#Sound_events
    sound: "block.note_block.bell"
    # Any decimal number between 0 and 1.
    volume: 1.0
    # Any decimal number between 0 and 2.
    pitch: 1.0
  
  # Display a title to the player who is mentioned.
  send-title:
    enabled: true
    # Type {mentioner} for the nickname of the person who mentioned you
    # Color formats are supported
    title: "&eYou have been mentioned"
    # Type {mentioner} for the nickname of the person who mentioned you
    # Color formats are supported
    subtitle: "&eby &6&l{mentioner}"
    duration:
      # The duration in ticks for the title to fade in.
      fade-in: 5
      # The duration in ticks for the title to stay on the screen.
      stay: 70
      # The duration in ticks for the title to fade out.
      fade-out: 5

  # The color of the mention in chat.
  # Set to "" to disable
  color: "&e"

updater:
  # Whether to notify admins for new snapshot releases. Admins will still be notified on stable releases.
  notify-on-dev-release: false