## DO NOT CHANGE THIS
internal:
  plugin-verion: "1.0-SNAPSHOT"
## DO NOT CHANGE THIS

# What name to use by default for both Minecraft and Discord
# This can be changed by the player as long as they have the permission discordnick.use
# Can either be "minecraft", "discord", or "off"
default-sync: discord