name: DiscordNickSync
version: 1.0
main: com.gozarproductions.discordnicksync.DiscordNickSync
commands:
  discordnick:
    description: Main command for DiscordNickSync.
    usage: |
      §6Usage:
      §e- §6/discordnick §e< discord | minecraft | off >
      §e- §6/discordnick sync §e[ all | <username> ]
      §e- §6/discordnick reload
    permission: discordnick.use
permissions:
  discordsync.use:
    description: Allows players to set their own Discord nickname sync mode.
    default: true
  discordsync.admin:
    description: Allows admins to run /discordnick sync for all players.
    default: op