name: DiscordNickSync
version: 1.0
main: com.gozarproductions.DiscordNickSync
api-version: 1.21
description: Syncs your Discord nickname with your Essentials nickname via DiscordSRV.
author: Erika Gozar
website: https://gozarproductions.com
depend: [DiscordSRV, Essentials]
commands:
  discordnick:
    description: Main command for DiscordNickSync.
    usage: |
      §6Usage:
      §e- §6/discordnick §e< discord | minecraft | off >
      §e- §6/discordnick sync §e[ all | <username> ]
      §e- §6/discordnick reload
    aliases: [dn, dnick, discnick]
    permission: discordnick.use
permissions:
  discordsync.use:
    description: Allows players to set their own nickname sync mode.
    default: true
  discordsync.admin:
    description: |
      §6Allows admins to:
      §e- Run §6/discordnick §esync for all players
      §e- Reload the config
    default: op
    children:
      discordsync.use: true