name: DiscordNickSync
version: 1.0.3
main: com.gozarproductions.DiscordNickSync
api-version: 1.21
description: Syncs your Discord nickname with your Essentials nickname via DiscordSRV.
author: Erika Gozar
website: https://gozarproductions.com
depend: [DiscordSRV, Essentials]
commands:
  discordnick:
    description: Main command for DiscordNickSync.
    usage: |
      §e- §6/discordnick §e< discord | minecraft | off >
      §e- §6/discordnick sync §e[ all | <username> ]
      §e- §6/discordnick reload
    aliases: [dn, dns, dnick, discnick]
    permission: discordnick.use
permissions:
  discordnick.use:
    description: |
      §6Allows players to:
      §e- Set their own nickname sync mode
      §e- Run §6/discordnick sync §efor themselves.
    default: true
  discordnick.admin:
    description: |
      §6Allows admins to:
      §e- Run §6/discordnick sync §efor all players or individual players
      §e- Reload the config
    default: op
    children:
      discordnick.use: true