name: Publish to Modrinth

on:
  release:
    types: [published]

jobs:
  upload-to-modrinth:
    runs-on: ubuntu-latest

    steps:
      - name: Get JAR asset name from release
        id: get-jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching release info..."
          api_url="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}"
          asset_info=$(curl -s -H "Authorization: token $GH_TOKEN" $api_url)
          jar_name=$(echo "$asset_info" | jq -r '.assets[] | select(.name | test("^discordnicksync-.*\\.jar$")) | .name' | head -n 1)

          if [ -z "$jar_name" ]; then
            echo "No .jar asset found in release!"
            exit 1
          fi

          echo "ASSET_NAME=$jar_name" >> $GITHUB_ENV

      - name: Download the JAR from the release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Downloading asset: $ASSET_NAME"
          download_url="https://api.github.com/repos/${{ github.repository }}/releases/assets"
          asset_id=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq '.assets[] | select(.name=="'"$ASSET_NAME"'") | .id')
          curl -L -H "Authorization: token $GH_TOKEN" -H "Accept: application/octet-stream" \
            "https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id" \
            -o "$ASSET_NAME"

      - name: Upload to Modrinth
        uses: RubixDev/modrinth-upload@v1
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project_id: tles3bfw
          version: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          changelog: ${{ github.event.release.body }}
          file_path: ${{ env.ASSET_NAME }}
          game_versions: '1.20,1.21'
          loaders: 'spigot,paper,purpur'
          featured: true
