name: Update Modrinth Description

on:
  push:
    branches:
      - main  # Or your actual branch

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load README.md into env variable
        run: |
          {
            echo 'README_CONTENT<<EOF'
            cat README.md
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Update Modrinth description
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          README_CONTENT: ${{ env.README_CONTENT }}
        run: |
          curl -X PATCH https://api.modrinth.com/v2/project/zE5EbgF4 \
            -H "Authorization: $MODRINTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg body "$README_CONTENT" '{ body: $body }')"
