name: Update Modrinth Description

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read README.md
        id: readme
        run: |
          DESCRIPTION=$(<README.md)
          DESCRIPTION="${DESCRIPTION//'%'/'%25'}"
          DESCRIPTION="${DESCRIPTION//$'\n'/'%0A'}"
          DESCRIPTION="${DESCRIPTION//$'\r'/'%0D'}"
          echo "content=$DESCRIPTION" >> "$GITHUB_OUTPUT"

      - name: Update Modrinth project description
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          curl -X PATCH https://api.modrinth.com/v2/project/tles3bfw \
            -H "Authorization: $MODRINTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"${{ steps.readme.outputs.content }}\"}"
