name: Update Modrinth Description

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read README.md
        id: readme
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat README.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update Modrinth project description
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          curl -X PATCH https://api.modrinth.com/v2/project/zE5EbgF4 \
          -H "Authorization: $MODRINTH_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$(jq -n --arg body "${{ steps.readme.outputs.content }}" '{ body: $body }')"
