name: Update Modrinth Description

on:
  push:
    branches:
      - main

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Modrinth project description
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          jq -Rs --arg body "$(cat README.md)" '{ body: $body }' > body.json

          curl -X PATCH https://api.modrinth.com/v2/project/tles3bfw \
            -H "Authorization: $MODRINTH_TOKEN" \
            -H "Content-Type: application/json" \
            --data @body.json
